if(EXISTS "/Users/mattiamontanari/repos/opengjk_3d/src/simd/build_float_minimal/tests/test_s1d[1]_tests.cmake")
  include("/Users/mattiamontanari/repos/opengjk_3d/src/simd/build_float_minimal/tests/test_s1d[1]_tests.cmake")
else()
  add_test(test_s1d_NOT_BUILT test_s1d_NOT_BUILT)
endif()
