if(EXISTS "/Users/mattiamontanari/repos/opengjk_3d/src/simd/build_float_wide/tests/test_crossval[1]_tests.cmake")
  include("/Users/mattiamontanari/repos/opengjk_3d/src/simd/build_float_wide/tests/test_crossval[1]_tests.cmake")
else()
  add_test(test_crossval_NOT_BUILT test_crossval_NOT_BUILT)
endif()
